---
- name: gather facts from the cloud
  hosts: workstation
  gather_facts: true
  roles:
  - name: osp-facts

- name: deploy frontends
  hosts: frontends
  become: yes
  roles:
    - name: 3tier-repo
    - name: frontends

- name: deploy apps
  hosts: apps
  become: yes
  roles:
    - name: 3tier-repo
    - name: apps

- name: deploy database
  hosts: appdbs
  become: yes
  roles:
    - name: 3tier-repo
    - name: appdbs
