---
# tasks file for appdbs
- name: install postgresql-server
  yum:
    name: postgresql-server
    state: latest
      
# NOTE: Unlike {{ posgresql_bin_dir }}/initdb, RHEL's postgresql-setup
# initdb does not overwrite existing data dir, so it is quite ok to
# re-run it. Also, it requires that root user run it.
- name: ensure postgresql database is initialized
  command: "postgresql-setup initdb"
  ignore_errors: yes

- name: enable and start postgresql
  service:
    name: postgresql.service
    state: started
    enabled: yes
