---
# tasks file for frontends
- name: install http and haproxy
  package:
    name: [ httpie, haproxy ]
    state: latest

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: enable haproxy
  service:
    name: haproxy
    state: started
    enabled: yes
