---
# tasks file for apps
- name: install tomcat and apache
  yum:
    name: [ tomcat, httpd ]
    state: latest

- name: create ansible tomcat directory
  file:
    path: "{{ tomcat_webapp_root }}"
    state: directory

- name: copy static index.html to tomcat webapps root dir
  template:
    src: index.html.j2
    dest: "{{ tomcat_webapp_root }}"/index.html
    mode: 0644

- name: enable and start tomcat and apache
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: 
    - tomcat
    - httpd
