---
# tasks file for apps
- name: install tomcat and apache
  yum:
    name: [ tomcat, httpd ]
    state: latest

- name: create ROOT webapp config dir
  file:
    path: "{{ tomcat_config_path }}"
    state: directory

- name: deploy ROOT webapp config
  template:
    src: ROOT.xml.j2
    dest: "{{ tomcat_config_path }}/ROOT.xml"
    mode: 0644

- name: create tomcat ROOT webapp root directory
  file:
    path: "{{ tomcat_webapp_root }}"
    state: directory

- name: copy static index.html to tomcat webapps root dir
  template:
    src: index.html.j2
    dest: "{{ tomcat_webapp_root }}/index.html"
    mode: 0644

- name: enable and start tomcat and apache
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: 
    - tomcat
    - httpd
